### ISSUE TITLE
error TS2307: Cannot find module 'nativescript-bottombar'.

### ISSUE THREAD

**Issue by gauravbabu74** [rhanbIT/nativescript-bottombar#1]
I am using Angular for creating native-script mobile app. I am facing following issue please check my project libraries information.
┌──────────────────┬─────────────────┬────────────────┬──────────────────┐
│ Component        │ Current version │ Latest version │ Information      │
│ nativescript     │ 2.5.0           │ 2.5.1          │ Update available │
│ tns-core-modules │ 2.5.1           │ 2.5.1          │ Up to date       │
│ tns-android      │ 2.5.0           │ 2.5.0          │ Up to date       │
│ tns-ios          │                 │ 2.5.0          │ Not installed    │

C:\Users\gaurav.babu\Desktop\BizNative\BizCase>tns run android
Executing before-prepare hook from C:\Users\gaurav.babu\Desktop\BizNative\BizCase\hooks\before-prepare\nativescript-dev-andr
oid-snapshot.js
Executing before-prepare hook from C:\Users\gaurav.babu\Desktop\BizNative\BizCase\hooks\before-prepare\nativescript-dev-type
script.js
Found peer TypeScript 2.1.6
app/modules/document/document.component.ts(25,45): error TS2307: Cannot find module 'nativescript-bottombar'.

node_modules/nativescript-bottombar/bottombar-common.d.ts(1,29): error TS2307: Cannot find module 'nativescript-bottombar'.

##########################################################################
My file is:
############################################################################

import { Component, ChangeDetectionStrategy, NgZone, OnInit, ViewChild, ElementRef, OnDestroy, EventEmitter, Input, Output } from '@angular/core';
import { Router } from "@angular/router";
import { Headers, RequestOptions, Http, Response, URLSearchParams } from '@angular/http';
import { RouterExtensions } from 'nativescript-angular/router';
import { Observable, BehaviorSubject } from "rxjs/Rx";
import { Page } from "ui/page";
import { request } from "http";
import * as appSettings from "application-settings";
import { XmltojsonService } from "../xmltojson.service";
import { MakeHashService } from "../services/makehash/makehash.service";
import { Document, DocumentService } from "./shared";
import { Backhandler } from "./models/backhandler.model";
import * as dialogs from "ui/dialogs";
import { connectionType, getConnectionType } from "connectivity";
import * as connectivity from "connectivity";
import * as Toast from 'nativescript-toast';
let imagepicker = require("nativescript-imagepicker");
import * as bghttp from "nativescript-background-http";
import { GestureEventData } from "ui/gestures";
import { Color } from "color";
import { ObservableArray } from "data/observable-array";
import { ListViewEventData, RadListView } from "nativescript-telerik-ui-pro/listview";
import {registerElement} from 'nativescript-angular/element-registry';
import {TITLE_STATE} from 'nativescript-bottombar/bottombar-common';
import {SelectedIndexChangedEventData} from 'nativescript-bottombar';
registerElement("BottomBar", () => require("nativescript-bottombar").BottomBar);
registerElement("BottomBarItem", () => require("nativescript-bottombar").BottomBar);

**Comment by rhanbIT** [comment]
Hi,

This a known issue but shouldn't block the build, does the build stop? Or nothing shows up ? (will fix it on sunday don't have time until then) 

```typescript 
registerElement("BottomBarItem", () => require("nativescript-bottombar").BottomBar);
``` 
this is not required 

Could you also provide the XML code? 
And the inner Component Class code?

Thank you for pulling this issue :smile:

**Comment by gauravbabu74** [comment]
Hi,

Are you updated above plugin ?
Build does not stop during debug process. I am using your given sample XML code just for checking plugin behavior till now.

<GridLayout rows="*, auto">
    <Label row="0" text="test"></Label>
    <GridLayout row="1">
        <BottomBar [items]="items" (tabSelected)="tabSelected($event)" [titleState]="titleState">
        </BottomBar>
    </GridLayout>
</GridLayout>

**Comment by rhanbIT** [comment]
Hi,

Did you try to remove and then add platform iOS or Android?

I finally didn't have time to fix this issue on sunday and won"t have time until a few days, I will give you a shoutout when this will be fixed.

**Comment by rhanbIT** [comment]
Oh forger to precise in the readme that you need to include a reference in the reference.d.ts from your project! Should work ☺

**Comment by rhanbIT** [comment]
the issue should be fixed from last update, no need to reference the module anymire neither ! tell me if you issue still occure, if it does could me send me a link to your repo? Thank you :smile:

**Comment by bismert** [comment]
Please can you provide an example with pure vanilla JS without Angular and TS please!

**Comment by rhanb** [comment]
Hi @bismert , unfortunately it's not my priority right now. I'll do it, but can't tell when !
But feel free to make a PR 😄
