### ISSUE TITLE
Cannot read property android of null, undefined

### ISSUE THREAD

**Issue by anuragd7** [rhanbIT/nativescript-bottombar#13]
Hi
I upgraded to NS 3.0 and created a new angular NS 3 project from the command line.
I subsequently installed the bottombar plugin and added the sample code from the plugin home page to app component.ts and html files.
When I run the project I get an error - Cannot read property android of null, undefined
Please take a look.

**Comment by anuragd7** [comment]
I got the problem- The image for the bottombar was not named correctly. Closing the issue.

**Comment by shiamalon** [comment]
same thing happened to me
