### ISSUE TITLE
Cannot read property 'android' of null, undefined

### ISSUE THREAD

**Issue by academici** [rhanbIT/nativescript-bottombar#18]
Hello, did everything as indicated in your example. On the screen of the emulator this message is displayed
![screenshot](https://user-images.githubusercontent.com/3863273/26942937-89d685da-4c8c-11e7-9ac6-8d57ff3a78e0.png)

**Comment by rhanbIT** [comment]
Hi,

Please look into closed issues before creating a new one, this one is already known. You have an issue with your images files, you don't initialise your BottomBarItem(s) the right way or you misplaced your files. Please provide sample code if this issue still occurred.

Thanks

**Comment by academici** [comment]
Thank you!
And can I use FontAwesome or svg?

**Comment by rhanbIT** [comment]
You can only use images files
