### ISSUE TITLE
Error with NativeScript 3.1 + Angular

### ISSUE THREAD

**Issue by borislemke** [rhanbIT/nativescript-bottombar#19]
I am getting this error when registering the module with NativeScript + Angular

```
node_modules/nativescript-bottombar/index.d.ts(3,10): error TS2305: Module '"{path-t-project}/node_modules/tns-core-modules/ui/core/bindable/bindable"' has no exported member 'Bindable'.
```

**Comment by borislemke** [comment]
I think the version on npm has not been yet updated. I will try to install the plugin from the git repo instead.

**Comment by rhanbIT** [comment]
Install the latest version of the plugin `3.04` ! this issue has already been fixed.

**Comment by borislemke** [comment]
@rhanbIT thanks for the reply. How do you install version `3.04`?
```
tns plugin add nativescript-bottombar@3.04
```
```
npm ERR! notarget No matching version found for nativescript-bottombar@3.04
```

**Comment by borislemke** [comment]
You had a typo, the new version is `3.0.4`, thanks for the hint.
