### ISSUE TITLE
SelectedIndexChangedEventData issue

### ISSUE THREAD

**Issue by dvdbrk** [rhanbIT/nativescript-bottombar#2]
Running the plugin with the default settings gives me:

`...error TS2305: Module '"....../node_modules/nativescript-bottombar/index"' has no exported member 'SelectedIndexChangedEventData'.` ?

**Comment by rhanbIT** [comment]
Try to import from `nativescript-bottombar/bottombar.common`

**Comment by dvdbrk** [comment]
Yes, it works with your solution

**Comment by rhanbIT** [comment]
Go back to `nativescript-bottombar` if you use the last version 😄
