### ISSUE TITLE
tns-core-modules/ui/core/bindable/bindable"' has no exported member 'Bindable'.

### ISSUE THREAD

**Issue by unclekitty** [rhanbIT/nativescript-bottombar#21]
![image](https://user-images.githubusercontent.com/4994802/27375629-5a151242-56a2-11e7-9278-88005ee47438.png)

**Comment by rhanbIT** [comment]
Please give me more specifications like the version number of the package you are using, which NativeScript version are you using etc..

**Comment by PolCPP** [comment]
Happening to me too, ns 3.0.3 but from what i can tell. the latest version on npm and the one that gets installed is 2.1.4 which i guess it's for NS2.

**Comment by rhanbIT** [comment]
The latest version for NS3 is `3.0.4`, this the one you should install.

**Comment by KingAndroid** [comment]
This issus is regressed
![image](https://user-images.githubusercontent.com/4363735/29254366-d0817ecc-80c6-11e7-862a-296dcb5caa01.png)
![image](https://user-images.githubusercontent.com/4363735/29254377-edfd9ada-80c6-11e7-90b4-388e63281a1c.png)

**Comment by rhanb** [comment]
Just look at the comment I made before closing the issue and you'll be all good.
