### ISSUE TITLE
Getting error node_modules/nativescript-bottombar/index.d.ts(3,10): error TS2305: Module '"/Users/user/ns_app/node_modules/tns-core-modules/ui/core/bindable/bindable"' has no exported member 'Bindable'.

### ISSUE THREAD

**Issue by tayalakansh** [rhanbIT/nativescript-bottombar#23]
Followed read me  in order to implement bottom bar, but I am getting below compilation error.

node_modules/nativescript-bottombar/index.d.ts(3,10): error TS2305: Module '"/Users/user/ns_app/node_modules/tns-core-modules/ui/core/bindable/bindable"' has no exported member 'Bindable'.
tns version - 3.0.3

**Comment by rhanbIT** [comment]
You are using NS3 and a version of this plugin which support NS2, install the 3.0.4 version 👍

**Comment by Sathyendra** [comment]
Thank you so much **rhanbIT**

I got the same issue, but resolved after version upgrade to 3.0.4 

$ tns plugin remove nativescript-bottombar
$ tns plugin add nativescript-bottombar@3.0.4

Thanks again for the nice plugin.

**Comment by rhanbIT** [comment]
You are welcome @Sathyendra  😄
