### ISSUE TITLE
Not found module problem in javascript version

### ISSUE THREAD

**Issue by cagatayoncul** [rhanbIT/nativescript-bottombar#24]
I am trying JS version of this module. But i am gettin this error.

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd"
    actionBarHidden="true"
    xmlns:btn="nativescript-bottombar"
    loaded="onNavigated" class="page">

    <StackLayout>

        <btn:BottomBar tabSelected="tabSelected" titleState="{{ titleStateValue }}" hide="{{ hidden}}" > 
  <btn:BottomBar.items>
    <btn:BottomBarItem title="Cake" icon="ic_cake_white_24dp" color="#4CAF50" />
    <btn:BottomBarItem title="Favorites" icon="ic_favorite_white_24dp" color="#2196F3" />
    <btn:BottomBarItem title="Settings" icon="ic_settings_white_24dp" color="#FF4081" />
  </btn:BottomBar.items>
</btn:BottomBar>

    </StackLayout>

</Page>

```

> An uncaught Exception occurred on "main" thread.
> com.tns.NativeScriptException: 
> Calling js method onClick failed
> 
> Error: Building UI from XML. @file:///app/views/map/map.xml:16:9
>  > Module '/data/data/com.ttt.sss/files/app/nativescript-bottombar' not found for element 'nativescript-bottombar:BottomBar'.
>    > com.tns.NativeScriptException: Failed to find module: "/data/data/com.ttt.sss/files/app/nativescript-bottombar", relative to: app//
>       com.tns.Module.resolvePathHelper(Module.java:146)
>     com.tns.Module.resolvePath(Module.java:55)
>     com.tns.Runtime.callJSMethodNative(Native Method)
>     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1043)
>     com.tns.Runtime.callJSMethodImpl(Runtime.java:925)
>     com.tns.Runtime.callJSMethod(Runtime.java:912)
>     com.tns.Runtime.callJSMethod(Runtime.java:896)
>     com.tns.Runtime.callJSMethod(Runtime.java:888)
>     com.tns.gen.java.lang.Object_frnal_ts_helpers_l58_c38__ClickListenerImpl.onClick(Object_frnal_ts_helpers_l58_c38__Click

**Comment by cagatayoncul** [comment]
Any suggestion does it compactibla with 3.1.x?

**Comment by rhanbIT** [comment]
Hi,

I'm not sure that this error comes from the plugin. And yes NS3 is supported, but you have to install the latest `3.x`version of this plugin. `2.x`is for NS2.
If you are under NS3 with the latest version of the plugin and it still doesn't work try to:
- `tns plugin remove nativescript-bottombar`
- `rm -rf platforms`
- `tns plugin add nativescript-bottombar@3.x`
- `tns run platform`

**Comment by cagatayoncul** [comment]
i tried everything. i tried on fresh install of NS3. But it doesnt work
properly. if i found a solution i will write.

8 Tem 2017 23:39 tarihinde "JB" <notifications@github.com> yazdı:

**Comment by rhanbIT** [comment]
Ok, then give me more informations like package version etc.. or a github repo or I won't be able to help.

**Comment by cagatayoncul** [comment]
Can you check my repo https://github.com/cagatayoncul/bottombartest

**Comment by cagatayoncul** [comment]
Ok i found a solution 
tns add plugin nativescript-bottom its gettin wrong version. i solved problem with this nativescript-bottombar@3.0.4
