### ISSUE TITLE
Feature Request: Missing badges/notifications

### ISSUE THREAD

**Issue by chimon2000** [rhanbIT/nativescript-bottombar#3]
Currently, the ability to set badge counts on items is not enabled.

```
// Customize notification (title, background, typeface)
bottomNavigation.setNotificationBackgroundColor(Color.parseColor("#F63D2B"));

// Add or remove notification for each item
bottomNavigation.setNotification("1", 3);
// OR
AHNotification notification = new AHNotification.Builder()
    .setText("1")
    .setBackgroundColor(ContextCompat.getColor(DemoActivity.this, R.color.color_notification_back))
    .setTextColor(ContextCompat.getColor(DemoActivity.this, R.color.color_notification_text))
     .build();
bottomNavigation.setNotification(notification, 1);
```

**Comment by rhanbIT** [comment]
Yep exactly,

This feature will come in the next update, unfortunately I am really busy with my company and studies! It will come in a few weeks! But feel free to make a PR if you want to participate to this plugin 😄

**Comment by rhanbIT** [comment]
You can now use notifications on the last version, the backgroundColor of the notification is not yet customisable! it will be in the next version :smile:
