### ISSUE TITLE
 Changing the selected Tab programmatically

### ISSUE THREAD

**Issue by GFAdmin** [rhanbIT/nativescript-bottombar#4]
Hi, thank you for a wonderful tool. It is rather a question than an issue. I am wondering if there is a possibility to change the selected Tab programmatically after the bar was loaded (for example, from the SideDrawer menu)? Thank you and all the best.

**Comment by rhanbIT** [comment]
Hi,

`this._bar.selectItem(0); // should work`

This should do what you need 😄
