### ISSUE TITLE
Nativescript-bttombar not compatible with Nativescript 3.0

### ISSUE THREAD

**Issue by teganscott** [rhanbIT/nativescript-bottombar#5]
Hi,
I've been trying to implement bottombar with my nativescript 3.0 release client based app.
It doesn't seem to be compatible yet as some of the class names have been renamed in the release candidate. Are there any plans to update the plugin to be compatible with nativescript 3.0?

Thank you,
Tegan

**Comment by rhanbIT** [comment]
Hey,

Yep it will, not my priority in my work though, feel free to make a PR :smile: ! 
Will be implemented at last when the 3.0 will be officially out!

**Comment by shanika** [comment]
I'll try to upgrade. Does it work for IOS at the moment?

**Comment by rhanbIT** [comment]
It does work on iOS but not release ready, I have a few modifications to bring! I'll finally get time this afternoon to work on this plugin, I will do a release with the iOS platform working and then an other one for the 3.0 support 💯
