### ISSUE TITLE
Getting below issue while initializing ios app

### ISSUE THREAD

**Issue by ignistechs** [rhanbIT/nativescript-bottombar#9]
CONSOLE LOG file:///app/app.component.js:29:20: tabLoaded
CONSOLE ERROR [native code]: ERROR TypeError: undefined is not an object (evaluating 'this.parent.get')

**Comment by rhanbIT** [comment]
Hi,

Could you provide your code please, like this I will be able to reproduce the error and fix it!

Thanks

**Comment by ignistechs** [comment]
Its the same code base of demo, i just changes the dependency to 3.0.0

**Comment by rhanbIT** [comment]
Can't reproduce the issue with the latest version of package
